# Default values for neo-helm-chart.
image:
  name: gcr.io/traefiklabs/neo-agent
  pullPolicy: IfNotPresent
  pullSecrets: []
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# User token to access to neo
token: "plop"

deployment:
  # Additional deployment annotations
  annotations: {}
  # Additional deployment labels
  labels: {}
  # Additional pods annotations
  podAnnotations: {}
  # Additional pods labels
  podLabels: {}
  args:
    - --log-level=debug
    - --platform-url=http://traefik.traefik.svc.cluster.local
    - --scrape-ip=172.18.0.5
    - --scrape-name=traefik
    - --scrape-kind=traefik

resources: {}
  # requests:
  #   cpu: "100m"
  #   memory: "50Mi"
  # limits:
  #   cpu: "300m"
  #   memory: "150Mi"
affinity: {}

nodeSelector: {}
tolerations: []

serviceAccount:
  name: ""
  # If set, an existing service account is used
  # If not set, a service account is created automatically using the fullname template
  annotations: {}

service:
  # Additional service annotations
  annotations: {}
  # Additional service labels
  labels: {}
