# Default values for neo-helm-chart.
image:
  name: gcr.io/traefiklabs/neo-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

deployment:
  annotations: {}
  # Additional deployment annotations
  labels: {}
  # Additional deployment labels
  podAnnotations: {}
  # Additional pods annotations
  podLabels: {}
  # Additional pods labels
  args: ["--log-level=debug", "--log-format=console"]

serviceAccount:
  name: ""
  # If set, an existing service account is used
  # If not set, a service account is created automatically using the fullname template
  annotations: {}

service:
  annotations: {}
  # Additional service annotations
  labels: {}
  # Additional service labels
