# Default values for neo-helm-chart.
image:
  name: gcr.io/traefiklabs/neo-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

deployment:
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  args: ["--log-level=debug", "--log-format=console"]

serviceAccount:
  name: "neo"
  create: true

service:
  annotations: {}
  labels: {}
