---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressclasses.neo.traefik.io
spec:
  group: neo.traefik.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Controller
          jsonPath: .spec.controller
          type: string
        - name: Is Default
          jsonPath: .metadata.annotations.ingressclass\.kubernetes\.io/is-default-class
          type: string
        - name: Age
          jsonPath: .metadata.creationTimestamp
          type: date
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                controller:
                  type: string
  scope: Cluster
  names:
    plural: ingressclasses
    singular: ingressclass
    kind: IngressClass
