---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neo-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "neo-helm-chart.name" . }}
    helm.sh/chart: {{ template "neo-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
