{{- if not .Values.serviceAccount.name -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "neo-helm-chart.serviceAccountName" . }}
  namespace: {{ .Release.namespace }} 
  labels:
    app.kubernetes.io/name: {{ template "neo-helm-chart.name" . }}
    helm.sh/chart: {{ template "neo-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
