---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-cert-sa
  labels:
    app.kubernetes.io/name: {{ template "neo-helm-chart.name" . }}
    helm.sh/chart: {{ template "neo-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-cert-sa-cluster-role
  labels:
    app.kubernetes.io/name: {{ template "neo-helm-chart.name" . }}
    helm.sh/chart: {{ template "neo-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
rules:
  - verbs:
      - get
      - create
      - patch
    resources:
      - mutatingwebhookconfigurations
    apiGroups:
      - admissionregistration.k8s.io
  - verbs:
      - get
      - create
      - delete
      - list
      - watch
    resources:
      - certificatesigningrequests
    apiGroups:
      - certificates.k8s.io
  - verbs:
      - update
    resources:
      - certificatesigningrequests/approval
    apiGroups:
      - certificates.k8s.io
  - verbs:
      - approve
    resourceNames:
      - kubernetes.io/*
    resources:
      - signers
    apiGroups:
      - certificates.k8s.io
  - verbs:
      - create
      - get
      - patch
      - update
    apiGroups:
      - ""
    resources:
      - secrets
  - verbs:
      - get
    apiGroups:
      - ""
    resources:
      - configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-cert-sa-role-binding
  labels:
    app.kubernetes.io/name: {{ template "neo-helm-chart.name" . }}
    helm.sh/chart: {{ template "neo-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-cert-sa-cluster-role
subjects:
  - kind: ServiceAccount
    name: webhook-cert-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-cert-setup
  labels:
    app.kubernetes.io/name: {{ template "neo-helm-chart.name" . }}
    helm.sh/chart: {{ template "neo-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: webhook-cert-sa
      containers:
        - name: webhook-cert-setup
          image: newrelic/k8s-webhook-cert-manager:1.3.2
          imagePullPolicy: IfNotPresent
          args:
            - ./generate_certificate.sh
            - --service
            - neo-agent 
            - --webhook
            - neo 
            - --secret
            - neo-certs
            - --namespace
            - {{ .Release.Namespace }}
      restartPolicy: Never
  backoffLimit: 0
