---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "neo-helm-chart.name" . }}
    helm.sh/chart: {{ template "neo-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.deployment.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.deployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: neo-agent
  template:
    metadata:
      labels:
        app: neo-agent 
      {{- with .Values.deployment.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with .Values.deployment.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: neo-agent
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: neo-agent
          env:
            - name: DISABLE_GIT_SSL_VERIFY
              value: "true"
          image: "{{ .Values.image.name }}:{{default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- with .Values.resources }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
          volumeMounts:
            - mountPath: /var/run/neo-agent/
              name: neo-certs
          args:
            - --token={{ required "A valid .Values.token is required." .Values.token }}
            - --auth-server.listen-addr=:80
            - --acp-server.listen-addr=:443
            - --acp-server.cert=/var/run/neo-agent/cert.pem
            - --acp-server.key=/var/run/neo-agent/key.pem
            - --acp-server.auth-server-addr=http://neo-agent.{{ .Release.Namespace }}.svc.cluster.local
          {{- with .Values.deployment.args }}
          {{- range . }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
      volumes:
        - name: neo-certs 
          secret:
            secretName: neo-certs 
            items:
              - key: cert
                path: cert.pem
              - key: key
                path: key.pem
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
