apiVersion: v1
kind: Service
metadata:
  name: {{ template "neo-helm-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "neo-helm-chart.name" . }}
    helm.sh/chart: {{ template "neo-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.deployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      name: neo-agent-webhook
    - port: 80
      name: neo-agent-auth
  selector:
    app: neo-agent
