---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-agent-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hub-helm-chart.name" . }}
    helm.sh/chart: {{ template "hub-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.controllerDeployment.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.controllerDeployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-agent
      component: controller
  template:
    metadata:
      labels:
        app: hub-agent
        component: controller
      {{- with .Values.controllerDeployment.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with .Values.controllerDeployment.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: hub-agent
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hub-agent-controller
          env:
            - name: DISABLE_GIT_SSL_VERIFY
              value: "true"
          image: "{{ .Values.image.name }}:{{default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 5
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            {{- with .Values.resources }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
          volumeMounts:
            - mountPath: /var/run/hub-agent/
              name: hub-certs
          args:
            - controller
            - --platform-url=https://platform.hub.traefik.io/agent
            - --token={{ required "A valid .Values.token is required." .Values.token }}
            - --acp-server.listen-addr=:443
            - --acp-server.cert=/var/run/hub-agent/cert.pem
            - --acp-server.key=/var/run/hub-agent/key.pem
            - --acp-server.auth-server-addr=http://hub-agent.{{ .Release.Namespace }}.svc.cluster.local
          {{- with .Values.controllerDeployment.args }}
          {{- range . }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
      volumes:
        - name: hub-certs
          secret:
            secretName: hub-certs
            items:
              - key: cert
                path: cert.pem
              - key: key
                path: key.pem
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
