---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-agent-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hub-helm-chart.name" . }}
    helm.sh/chart: {{ template "hub-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
  {{- with .Values.gatewayDeployment.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.gatewayDeployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-agent
      component: gateway
  template:
    metadata:
      labels:
        app: hub-agent
        component: gateway
      {{- with .Values.gatewayDeployment.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with .Values.gatewayDeployment.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: hub-agent-gateway
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hub-agent-gateway
          image: "{{ .Values.image.name }}:{{default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- with .Values.resources }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
          args:
            - gateway
            - --token={{ required "A valid .Values.token is required." .Values.token }}
            - --gateway-addr=:443
            - --dns-addr=:53
          {{- with .Values.gatewayDeployment.args }}
          {{- range . }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
