---
apiVersion: v1
kind: Service
metadata:
  name: hub-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hub-helm-chart.name" . }}
    helm.sh/chart: {{ template "hub-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.deployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      name: hub-agent-webhook
    - port: 80
      name: hub-agent-auth
  selector:
    app: hub-agent
