{{- $cert := "" }}
{{- $key := "" }}
{{- $host := printf "hub-agent-controller.%s.svc" .Release.Namespace }}

{{- $crtSecret := lookup "v1" "Secret" .Release.Namespace "hub-agent-certs" }}
{{ if $crtSecret }}
  {{- $cert = b64dec $crtSecret.data.cert  }}
  {{- $key = b64dec $crtSecret.data.key  }}
{{ else }}
  {{- $crt := genSelfSignedCert $host (list) (list $host) (int .Values.admissionWebhook.certValidity) }}
  {{- $cert = $crt.Cert  }}
  {{- $key = $crt.Key  }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hub-agent-certs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hub-helm-chart.name" . }}
    helm.sh/chart: {{ template "hub-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  cert: {{ b64enc (trim $cert) }}
  key: {{ b64enc (trim $key) }}

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hub-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hub-helm-chart.name" . }}
    helm.sh/chart: {{ template "hub-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
webhooks:
  - name: hub-agent.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: hub-agent-controller
        namespace: {{ .Release.Namespace }}
        path: /ingress
      caBundle: {{ b64enc (trim $cert) }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - extensions
        apiVersions:
          - v1beta1
        resources:
          - ingresses
        scope: Namespaced
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1beta1
        resources:
          - ingresses
        scope: Namespaced
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        resources:
          - ingresses
        scope: Namespaced
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - traefik.containo.us
        apiVersions:
          - v1alpha1
        resources:
          - ingressroutes
        scope: Namespaced

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hub-edge-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hub-helm-chart.name" . }}
    helm.sh/chart: {{ template "hub-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
webhooks:
  - name: hub-agent.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: hub-agent-controller
        namespace: {{ .Release.Namespace }}
        path: /edge-ingress
      caBundle: {{ b64enc (trim $cert) }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - hub.traefik.io
        apiVersions:
          - v1alpha1
        resources:
          - edgeingresses
        scope: Namespaced

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: hub-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hub-helm-chart.name" . }}
    helm.sh/chart: {{ template "hub-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
webhooks:
  - name: hub-agent.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: hub-agent-controller
        namespace: {{ .Release.Namespace }}
        path: /ingress/validation
      caBundle: {{ b64enc (trim $cert) }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - extensions
        apiVersions:
          - v1beta1
        resources:
          - ingresses
        scope: Namespaced
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1beta1
        resources:
          - ingresses
        scope: Namespaced
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        resources:
          - ingresses
        scope: Namespaced
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - traefik.containo.us
        apiVersions:
          - v1alpha1
        resources:
          - ingressroutes
        scope: Namespaced

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hub-acp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hub-helm-chart.name" . }}
    helm.sh/chart: {{ template "hub-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
webhooks:
  - name: hub-agent.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: hub-agent-controller
        namespace: {{ .Release.Namespace }}
        path: /acp
      caBundle: {{ b64enc (trim $cert) }}
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - hub.traefik.io
        apiVersions:
          - v1alpha1
        resources:
          - accesscontrolpolicies
