---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-agent-tunnel
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hub-helm-chart.name" . }}
    helm.sh/chart: {{ template "hub-helm-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tunnel
  {{- with .Values.tunnelDeployment.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.tunnelDeployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.tunnelDeployment.replicas }}
  selector:
    matchLabels:
      app: hub-agent
      component: tunnel
  template:
    metadata:
      labels:
        app: hub-agent
        component: tunnel
      {{- with .Values.tunnelDeployment.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with .Values.tunnelDeployment.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: hub-agent-tunnel
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hub-agent-tunnel
          image: "{{ .Values.image.name }}:{{default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- with .Values.resources }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
          args:
            - tunnel
            - --token={{ required "A valid .Values.token is required." .Values.token }}
            {{- if .Values.tunnelDeployment.traefik -}}
            {{- if .Values.tunnelDeployment.traefik.tunnelHost -}}
            - --traefik.tunnel-host={{ .Values.tunnelDeployment.traefik.tunnelHost -}}
            {{- end -}}
            {{- if .Values.tunnelDeployment.traefik.tunnelPort -}}
            - --traefik.tunnel-port={{ .Values.tunnelDeployment.traefik.tunnelPort -}}
            {{- end -}}
            {{- end -}}
          {{- with .Values.tunnelDeployment.args }}
          {{- range . }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
