---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-agent-tunnel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: tunnel
  {{- with .Values.tunnelDeployment.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.tunnelDeployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.tunnelDeployment.replicas }}
  selector:
    matchLabels:
      app: hub-agent
      component: tunnel
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hub-agent
        component: tunnel
      {{- with .Values.tunnelDeployment.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with .Values.tunnelDeployment.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: hub-agent-tunnel
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hub-agent-tunnel
          image: {{ template "hub-helm-chart.image-name" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - tunnel
            {{ if .Values.tokenSecretRef -}}
            - --token=$(HUB_SECRET_TOKEN)
            {{ else -}}
            - --token={{ required "A valid .Values.token or .Values.tokenSecretRef is required." .Values.token }}
            {{ end -}}
            - --traefik.tunnel-host={{ required "A valid .Values.tunnelDeployment.traefik.tunnelHost is required." .Values.tunnelDeployment.traefik.tunnelHost }}
            - --traefik.tunnel-port={{ .Values.tunnelDeployment.traefik.tunnelPort }}
          {{- with .Values.tunnelDeployment.args -}}
          {{- range . }}
            - {{ . | quote }}
          {{ end }}
          {{ end }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          env:
            {{- if .Values.tokenSecretRef }}
            - name: HUB_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- with .Values.tokenSecretRef }}
                  {{- toYaml . | nindent 18 }}
                  {{- end -}}
            {{- end }}
          resources:
            {{- with .Values.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
