name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run
        run: |
          curl -L https://git.io/get_helm.sh | bash -s -- -v v3.5.3
          curl -sSL -o /tmp/ct.tgz https://github.com/helm/chart-testing/releases/download/v3.3.1/chart-testing_3.3.1_linux_amd64.tar.gz
          tar xzf /tmp/ct.tgz -C /tmp && sudo cp /tmp/ct /usr/local/bin/ct && command -v ct
          make
